import Head from 'next/head'
import { ReactElement } from 'react';

import Footer from '../footer';
import Header from '../header';

interface ILayout {
  children: ReactElement
}

const Layout = ({ children }: ILayout) => {
  return (
    <>
      <Head>
        <title>Wlad.me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p className="text-red-500 text-lg text-center underline">!Site is under construction!</p>

      <div className="w-full px-8 py-16 bg-cyan-50">
        <Header />

        <main className="flex flex-col items-center">{children}</main>

        {/*<Footer />*/}
      </div>
    </>
  )
}

export default Layout
